    hc: 0.108922137
    gravity: 9.80665
    dt: 0.01
    MaxStepX: 0.03
    MinStepX: -0.03
    MaxStepY: 0.11
    MinStepY: 0.08
    MaxStepZ: 0.02
    Tss: 0.1
    Tds: 0.2
    HX: 0.000
    HY: 0.000
    HZ: 0.000
    Q: 1
    R: 1.0e-7
    Np: 152
    debug: True